# Generated by Django 5.2.10 on 2026-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_system_template_revamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Message content with {variable} placeholders'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='variable_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Maps positional {{1}},{{2}} to Rivo variable names, e.g. {"1": "first_name", "2": "bank_name"}'),
        ),
    ]
