# Generated by Django 5.2.10 on 2026-02-10 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition_channels', '0010_channel_monthly_spend'),
        ('campaigns', '0003_swap_subsource_to_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Attribution source for leads from this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='acquisition_channels.source'),
        ),
    ]
