# Generated by Django 5.2.10 on 2026-02-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_add_case_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='stage',
            field=models.CharField(choices=[('processing', 'Processing'), ('submitted_to_bank', 'Submitted to Bank'), ('under_review', 'Under Review'), ('submitted_to_credit', 'Submitted to Credit'), ('preapproved', 'Preapproved'), ('valuation_initiated', 'Valuation Initiated'), ('valuation_report_received', 'Valuation Report Received'), ('fol_requested', 'FOL Requested'), ('fol_received', 'FOL Received'), ('fol_signed', 'FOL Signed'), ('disbursed', 'Disbursed'), ('final_documents', 'Final Documents'), ('mc_received', 'MC Received'), ('sales_queries', 'Sales Queries'), ('credit_queries', 'Credit Queries'), ('disbursal_queries', 'Disbursal Queries'), ('on_hold', 'On Hold'), ('property_transferred', 'Property Transferred'), ('rejected', 'Rejected'), ('not_proceeding', 'Not Proceeding')], default='processing', help_text='Current stage of the case', max_length=30),
        ),
        migrations.AlterField(
            model_name='clienttocaseslaconfig',
            name='breach_percent',
            field=models.PositiveIntegerField(default=120, help_text='Percentage of SLA time at which to flag as breached'),
        ),
        migrations.AlterField(
            model_name='stageslaconfig',
            name='breach_percent',
            field=models.PositiveIntegerField(default=120, help_text='Percentage of SLA time at which to flag as breached (e.g., 120 = breach at 120% of SLA)'),
        ),
        migrations.AlterField(
            model_name='stageslaconfig',
            name='from_stage',
            field=models.CharField(choices=[('processing', 'Processing'), ('submitted_to_bank', 'Submitted to Bank'), ('under_review', 'Under Review'), ('submitted_to_credit', 'Submitted to Credit'), ('preapproved', 'Preapproved'), ('valuation_initiated', 'Valuation Initiated'), ('valuation_report_received', 'Valuation Report Received'), ('fol_requested', 'FOL Requested'), ('fol_received', 'FOL Received'), ('fol_signed', 'FOL Signed'), ('disbursed', 'Disbursed'), ('final_documents', 'Final Documents'), ('mc_received', 'MC Received'), ('sales_queries', 'Sales Queries'), ('credit_queries', 'Credit Queries'), ('disbursal_queries', 'Disbursal Queries'), ('on_hold', 'On Hold'), ('property_transferred', 'Property Transferred'), ('rejected', 'Rejected'), ('not_proceeding', 'Not Proceeding')], help_text='The stage this SLA applies to', max_length=50),
        ),
        migrations.AlterField(
            model_name='stageslaconfig',
            name='to_stage',
            field=models.CharField(choices=[('processing', 'Processing'), ('submitted_to_bank', 'Submitted to Bank'), ('under_review', 'Under Review'), ('submitted_to_credit', 'Submitted to Credit'), ('preapproved', 'Preapproved'), ('valuation_initiated', 'Valuation Initiated'), ('valuation_report_received', 'Valuation Report Received'), ('fol_requested', 'FOL Requested'), ('fol_received', 'FOL Received'), ('fol_signed', 'FOL Signed'), ('disbursed', 'Disbursed'), ('final_documents', 'Final Documents'), ('mc_received', 'MC Received'), ('sales_queries', 'Sales Queries'), ('credit_queries', 'Credit Queries'), ('disbursal_queries', 'Disbursal Queries'), ('on_hold', 'On Hold'), ('property_transferred', 'Property Transferred'), ('rejected', 'Rejected'), ('not_proceeding', 'Not Proceeding')], help_text='The expected next stage', max_length=50),
        ),
    ]
