# Generated by Django 5.2.10 on 2026-02-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_add_phone_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='mortgage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Requested mortgage amount (optional)', max_digits=12, null=True),
        ),
    ]
