# Generated by Django 5.2.10 on 2026-02-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_add_mortgage_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pipeline_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('declined', 'Declined')], default='submitted', help_text='External-facing pipeline status across Lead → Client → Case', max_length=20),
        ),
    ]
