# Generated by Django 5.2.10 on 2026-02-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_add_pipeline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='pipeline_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('submitted_to_bank', 'Submitted to Bank'), ('preapproved', 'Preapproved'), ('fol_received', 'FOL Received'), ('disbursed', 'Disbursed'), ('declined', 'Declined')], default='submitted', help_text='External-facing pipeline status across Lead → Client → Case', max_length=20),
        ),
    ]
