# Generated by Django 5.2.10 on 2026-03-20 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_phone_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the invite email was last sent', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry timestamp for the invite token (24 hours from creation)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_token_hash',
            field=models.CharField(blank=True, default='', help_text='SHA256 hash of invite token for password setup', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the user has set their password via email invite'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='User email address (unique, required)', max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, default='', help_text='Bcrypt hash of password', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Username for login (auto-generated from name)', max_length=50, unique=True),
        ),
    ]
